[package]
name = "lca2019"
version = "0.1.0"
authors = ["Wesley Moore <wes@wezm.net>"]
edition = "2018"

[dependencies]
profont = "0.1"
ssd1675 = "0.1"
embedded-graphics = "0.4"
linux-embedded-hal = "0.2"
